function tests = test_q_coefficient_validation
%TEST_Q_COEFFICIENT_VALIDATION Verify coefficient counts and admissible domains.

tests = functiontests(localfunctions);
end

function testAcceptsAdmissibleCoefficients(~)
validCases = { ...
    'constant', 2; ...
    'q const', 2; ...
    'frac1', [10 0.01]; ...
    'frac1', [-10 -2]; ...
    'frac2', [10 0.01]; ...
    'frac2', [-10 -2]; ...
    'exp', 1; ...
    'q_exp', -1 ...
};

for idx = 1:size(validCases, 1)
    Validate_Q_Coefficients(validCases{idx, 1}, validCases{idx, 2}, ...
        'test_q_coefficient_validation');
end
end

function testRejectsIncorrectCoefficientCounts(testCase)
invalidCases = { ...
    'constant', [1 2]; ...
    'frac1', 1; ...
    'frac1', [1 2 3]; ...
    'frac2', 1; ...
    'frac2', [1 2 3]; ...
    'exp', [1 2] ...
};

VerifyInvalidCases(testCase, invalidCases);
end

function testRejectsNonPositiveConstant(testCase)
VerifyInvalidCases(testCase, {'constant', 0; 'constant', -1});
end

function testRejectsSingularOrNonPositiveLinearFraction(testCase)
invalidCases = { ...
    'frac1', [1 0]; ...
    'frac1', [1 -0.5]; ...
    'frac1', [1 -1]; ...
    'frac1', [-1 1]; ...
    'frac1', [1 -2] ...
};

VerifyInvalidCases(testCase, invalidCases);
end

function testRejectsSingularOrNonPositiveQuadraticFraction(testCase)
invalidCases = { ...
    'frac2', [1 0]; ...
    'frac2', [1 -0.5]; ...
    'frac2', [1 -1]; ...
    'frac2', [-1 1]; ...
    'frac2', [1 -2] ...
};

VerifyInvalidCases(testCase, invalidCases);
end

function testRejectsZeroExponentialParameter(testCase)
VerifyInvalidCases(testCase, {'exp', 0});
end

function testPublicEntryPointsApplyAdmissibilityRules(testCase)
verifyError(testCase, @() Validate_Input( ...
    'exp', 0, 1, 0, 0, 4), 'Validate_Input:InvalidQCoeff');
verifyError(testCase, @() Build_Problem_Data( ...
    4, 'frac1', 1, [1 -0.5], 0, 0), ...
    'Build_Problem_Data:InvalidQCoeff');
verifyError(testCase, @() Compute_FEM_Data( ...
    4, 'constant', [1 2], 1, 0, 0), ...
    'Compute_FEM_Data:InvalidQCoeff');
verifyError(testCase, @() Def_Problem( ...
    4, 'frac2', 1, [1 -1], 0, 0), ...
    'Def_Problem:InvalidQCoeff');
end

function testAliasesNormalizeToCanonicalTypes(~)
assert(strcmp(Normalize_Q_Type('constant'), 'q_const'));
assert(strcmp(Normalize_Q_Type('frac1'), ...
    'q_frac_with_denom_1st_degree'));
assert(strcmp(Normalize_Q_Type('frac2'), ...
    'q_frac_with_denom_2nd_degree'));
assert(strcmp(Normalize_Q_Type('exponential'), 'q_exp'));
end

function VerifyInvalidCases(testCase, invalidCases)
for idx = 1:size(invalidCases, 1)
    verifyError(testCase, @() Validate_Q_Coefficients( ...
        invalidCases{idx, 1}, invalidCases{idx, 2}, ...
        'test_q_coefficient_validation'), ...
        'test_q_coefficient_validation:InvalidQCoeff');
end
end