function status = evaluate_performance_guardrail(timings, memoryStats, baseline)
%EVALUATE_PERFORMANCE_GUARDRAIL Evaluate runtime and memory observations.

assert(isnumeric(timings) && size(timings, 2) == 4, ...
    'evaluate_performance_guardrail:InvalidTimings', ...
    'timings must have four columns.');
assert(isnumeric(memoryStats) && size(memoryStats, 2) == 4 ...
    && size(memoryStats, 1) == size(timings, 1), ...
    'evaluate_performance_guardrail:InvalidMemoryStats', ...
    'memoryStats must align with timings and have four columns.');
assert(isstruct(baseline) ...
    && numel(baseline.numElementsList) == size(timings, 1), ...
    'evaluate_performance_guardrail:InvalidBaseline', ...
    'baseline mesh sizes must align with observations.');

numElements = timings(:, 1);
assert(isequal(numElements, baseline.numElementsList(:)) ...
    && isequal(memoryStats(:, 1), numElements), ...
    'evaluate_performance_guardrail:MeshMismatch', ...
    'Observed and baseline mesh sizes must match.');

medianSeconds = timings(:, 3);
memoryRatio = memoryStats(:, 4);
runtimeThresholds = baseline.medianThresholdSeconds(:);
memoryThresholds = baseline.memoryThresholdRatio(:);
isRuntimeOver = medianSeconds > runtimeThresholds;
isMemoryOver = memoryRatio > memoryThresholds;

status = struct( ...
    'baselineVersion', baseline.version, ...
    'numElementsList', numElements, ...
    'medianSeconds', medianSeconds, ...
    'referenceMedianSeconds', baseline.referenceMedianSeconds(:), ...
    'medianToReferenceRatio', ...
        medianSeconds ./ baseline.referenceMedianSeconds(:), ...
    'thresholdSeconds', runtimeThresholds, ...
    'sparseToDenseRatio', memoryRatio, ...
    'memoryThresholdRatio', memoryThresholds, ...
    'isRuntimeOverThreshold', isRuntimeOver, ...
    'isMemoryOverThreshold', isMemoryOver, ...
    'overCount', sum(isRuntimeOver | isMemoryOver));
end