function uFEM = Build_Local_Solution(degree, numElements, a, psi)
%BUILD_LOCAL_SOLUTION Assemble per-element FEM basis combinations.

assert(isnumeric(degree) && isscalar(degree) && any(degree == [1 3]), ...
    'Build_Local_Solution:InvalidDegree', ...
    'degree must be 1 or 3.');
assert(isnumeric(numElements) && isscalar(numElements) && numElements > 0 ...
    && mod(numElements, 1) == 0, ...
    'Build_Local_Solution:InvalidNumElements', ...
    'numElements must be a positive integer scalar.');
assert(iscell(psi) && numel(psi) >= 2, ...
    'Build_Local_Solution:InvalidBasis', ...
    'psi must contain at least two basis function handles.');
assert(isnumeric(a) && isvector(a), ...
    'Build_Local_Solution:InvalidCoefficients', ...
    'a must be a numeric vector.');
expectedLength = numElements + 1;
if degree == 3
    expectedLength = expectedLength + numElements + 1;
end
assert(numel(a) >= expectedLength, ...
    'Build_Local_Solution:InvalidCoefficients', ...
    'a must contain enough coefficients for the requested degree and mesh.');

uFEM = cell(numElements, 1);

if degree == 1
    for elemNo = 1:numElements
        uFEM{elemNo} = @(y) a(elemNo) * psi{1}(y) + a(elemNo + 1) * psi{2}(y);
    end
    return;
end

for elemNo = 1:numElements
    uFEM{elemNo} = @(y) a(elemNo) * psi{1}(y) + a(elemNo + 1) * psi{2}(y) ...
        + a(elemNo + numElements + 1) * psi{3}(y) + a(elemNo + numElements + 2) * psi{4}(y);
end
