function fem_Data = Compute_FEM_Data(numElements, q_Type, q_Coeff, load_Coeff, delta, P)
%COMPUTE_FEM_DATA Compute FEM solutions and error metrics without plotting.
%
%   fem_Data = COMPUTE_FEM_DATA(numElements, q_Type, q_Coeff, ...
%       load_Coeff, delta, P) returns a struct with mesh parameters,
%   exact solution, local FEM fields, and L2-style error summaries.

assert(isnumeric(numElements) && isvector(numElements) && ~isempty(numElements), ...
    'Compute_FEM_Data:InvalidNumElements', ...
    'numElements must be a non-empty numeric vector.');
assert(all(numElements > 0) && all(mod(numElements, 1) == 0), ...
    'Compute_FEM_Data:InvalidNumElements', ...
    'numElements must contain positive integers.');
assert((ischar(q_Type) || isstring(q_Type)) && strlength(string(q_Type)) > 0, ...
    'Compute_FEM_Data:InvalidQType', ...
    'q_Type must be a non-empty char or string.');
assert(isnumeric(q_Coeff) && ~isempty(q_Coeff), ...
    'Compute_FEM_Data:InvalidQCoeff', ...
    'q_Coeff must be a non-empty numeric array.');
assert(isnumeric(load_Coeff) && ~isempty(load_Coeff), ...
    'Compute_FEM_Data:InvalidLoadCoeff', ...
    'load_Coeff must be a non-empty numeric array.');
assert(isnumeric(delta) && isscalar(delta) && isnumeric(P) && isscalar(P), ...
    'Compute_FEM_Data:InvalidBoundaryData', ...
    'delta and P must be numeric scalars.');

% Define problem data and allocate per-mesh solution containers.
[meshSize, solutionSize, qFunc, loadFunc, x, ...
    uFEMLin, uFEMCub, uExact, relTol] = ...
    Def_Problem(numElements, q_Type, load_Coeff, q_Coeff, delta, P);

normalizedQType = Normalize_Q_Type(q_Type);

for idx = 1:numel(numElements)
    [uFEMLin{idx}, uFEMCub{idx}] = Calc_FEM_Sol( ...
        numElements(idx), meshSize(idx), delta, P, qFunc, loadFunc, relTol);
end

[sq_Error_Lin, sq_Error_Cub, conv_Factor_Lin, conv_Factor_Cub] = ...
    Compute_Error_Summary(numElements, uExact, uFEMLin, uFEMCub, relTol);

fem_Data = struct( ...
    'num_Elements', numElements, ...
    'mesh_Size', meshSize, ...
    'q_Type', normalizedQType, ...
    'solution_Size', solutionSize, ...
    'x', x, ...
    'u_Exact', uExact, ...
    'u_FEM_Lin', {uFEMLin}, ...
    'u_FEM_Cub', {uFEMCub}, ...
    'rel_Tol', relTol, ...
    'sq_Error_Lin', sq_Error_Lin, ...
    'sq_Error_Cub', sq_Error_Cub, ...
    'conv_Factor_Lin', conv_Factor_Lin, ...
    'conv_Factor_Cub', conv_Factor_Cub);

assert(numel(fem_Data.u_FEM_Lin) == numel(numElements), ...
    'Compute_FEM_Data:InvalidOutput', ...
    'Linear FEM output cell count must match numElements length.');
assert(numel(fem_Data.u_FEM_Cub) == numel(numElements), ...
    'Compute_FEM_Data:InvalidOutput', ...
    'Cubic FEM output cell count must match numElements length.');
assert(isa(fem_Data.u_Exact, 'function_handle'), ...
    'Compute_FEM_Data:InvalidOutput', ...
    'u_Exact output must be a function handle.');
assert(all(isfinite(fem_Data.sq_Error_Lin)) && all(isfinite(fem_Data.sq_Error_Cub)), ...
    'Compute_FEM_Data:InvalidOutput', ...
    'Computed error summaries must be finite.');

function [sq_Error_Lin, sq_Error_Cub, conv_Factor_Lin, conv_Factor_Cub] = ...
    Compute_Error_Summary(no_Of_Elements, u_Exact, u_FEM_Lin, u_FEM_Cub, relTol)

size_N = length(no_Of_Elements);
tot_Error = zeros(2, size_N);

for size_Ind = 1:1:size_N
    N = no_Of_Elements(size_Ind);
    tot_Error(1, size_Ind) = Integrate_Squared_Error( ...
        u_Exact, u_FEM_Lin{size_Ind}, N, relTol);
    tot_Error(2, size_Ind) = Integrate_Squared_Error( ...
        u_Exact, u_FEM_Cub{size_Ind}, N, relTol);
end

tot_Error = sqrt(tot_Error);
sq_Error_Lin = tot_Error(1, :);
sq_Error_Cub = tot_Error(2, :);

if size_N > 1
    conv_Factor = tot_Error(:, 1:end - 1) ./ tot_Error(:, 2:end);
    conv_Factor_Lin = conv_Factor(1, :);
    conv_Factor_Cub = conv_Factor(2, :);
else
    conv_Factor_Lin = [];
    conv_Factor_Cub = [];
end

function sq_Error = Integrate_Squared_Error(u_Exact, local_Fields, N, relTol)

h = 1 / N;
sq_Error = 0;

for elem_No = 1:N
    global_Coord = @(y) (elem_No - 1 + y) .* h;
    sq_Error_Local = @(y) ...
        (u_Exact(global_Coord(y)) - local_Fields{elem_No}(y)).^2;
    sq_Error = sq_Error + quadgk(sq_Error_Local, 0, 1, 'RelTol', relTol);
end