function [l2_Error_Lin, l2_Error_Cub, conv_Factor_Lin, conv_Factor_Cub] = ...
    Compute_Error_Summary(numElements, uExact, uFEMLin, uFEMCub, relTol)
%COMPUTE_ERROR_SUMMARY Compute L2 error norms and convergence factors.
%
%   [l2_Error_Lin, l2_Error_Cub, conv_Factor_Lin, conv_Factor_Cub] = ...
%       COMPUTE_ERROR_SUMMARY(numElements, uExact, uFEMLin, uFEMCub, relTol)
%   summarizes the FEM solution quality for each mesh.

assert(isnumeric(numElements) && isvector(numElements) && ~isempty(numElements), ...
    'Compute_Error_Summary:InvalidNumElements', ...
    'numElements must be a non-empty numeric vector.');
assert(isa(uExact, 'function_handle'), ...
    'Compute_Error_Summary:InvalidExactSolution', ...
    'uExact must be a function handle.');
assert(iscell(uFEMLin) && iscell(uFEMCub), ...
    'Compute_Error_Summary:InvalidFEMFields', ...
    'FEM field inputs must be cell arrays.');
size_N = length(numElements);
assert(numel(uFEMLin) == size_N && numel(uFEMCub) == size_N, ...
    'Compute_Error_Summary:InvalidFEMFieldCount', ...
    'FEM field inputs must provide one entry per mesh size.');
isValidFEMFields = @(fieldsByMesh) all(cellfun(@(localFields) ...
    iscell(localFields) && all(cellfun(@(f) isa(f, 'function_handle'), localFields)), fieldsByMesh));
assert(isValidFEMFields(uFEMLin) && isValidFEMFields(uFEMCub), ...
    'Compute_Error_Summary:InvalidFEMFields', ...
    'Each mesh entry must contain local function handles.');
assert(isnumeric(relTol) && isscalar(relTol) && relTol > 0, ...
    'Compute_Error_Summary:InvalidRelTol', ...
    'relTol must be a positive numeric scalar.');
assert(isfinite(relTol), ...
    'Compute_Error_Summary:InvalidRelTol', ...
    'relTol must be finite.');
squaredError = zeros(2, size_N);

for size_Ind = 1:size_N
    N = numElements(size_Ind);
    squaredError(1, size_Ind) = Integrate_Squared_Error( ...
        uExact, uFEMLin{size_Ind}, N, relTol);
    squaredError(2, size_Ind) = Integrate_Squared_Error( ...
        uExact, uFEMCub{size_Ind}, N, relTol);
end

l2Error = sqrt(squaredError);
l2_Error_Lin = l2Error(1, :);
l2_Error_Cub = l2Error(2, :);

if size_N > 1
    conv_Factor = l2Error(:, 1:end - 1) ./ l2Error(:, 2:end);
    conv_Factor_Lin = conv_Factor(1, :);
    conv_Factor_Cub = conv_Factor(2, :);
else
    conv_Factor_Lin = [];
    conv_Factor_Cub = [];
end

function sq_Error = Integrate_Squared_Error(uExact, localFields, N, relTol)

h = 1 / N;
sq_Error = 0;

for elemNo = 1:N
    globalCoord = @(y) (elemNo - 1 + y) .* h;
    sq_ErrorLocal = @(y) ...
        (uExact(globalCoord(y)) - localFields{elemNo}(y)).^2;
    sq_Error = sq_Error + h * quadgk(sq_ErrorLocal, 0, 1, 'RelTol', relTol);
end
