function fem_Data = Compute_FEM_Data(numElements, q_Type, q_Coeff, load_Coeff, delta, P)
%COMPUTE_FEM_DATA Compute FEM solutions and error metrics without plotting.
%
%   fem_Data = COMPUTE_FEM_DATA(numElements, q_Type, q_Coeff, ...
%       load_Coeff, delta, P) returns a struct with mesh parameters,
%   exact solution, local FEM fields, and L2 error norms.

assert(isnumeric(numElements) && isvector(numElements) && ~isempty(numElements), ...
    'Compute_FEM_Data:InvalidNumElements', ...
    'numElements must be a non-empty numeric vector.');
assert(all(numElements > 0) && all(mod(numElements, 1) == 0), ...
    'Compute_FEM_Data:InvalidNumElements', ...
    'numElements must contain positive integers.');
isValidQType = (ischar(q_Type) && size(q_Type, 1) == 1 && ~isempty(q_Type)) ...
    || (isstring(q_Type) && isscalar(q_Type) && strlength(q_Type) > 0);
assert(isValidQType, ...
    'Compute_FEM_Data:InvalidQType', ...
    'q_Type must be a non-empty char or string.');
normalizedQType = Validate_Q_Coefficients( ...
    q_Type, q_Coeff, 'Compute_FEM_Data');
assert(isnumeric(load_Coeff) && ~isempty(load_Coeff), ...
    'Compute_FEM_Data:InvalidLoadCoeff', ...
    'load_Coeff must be a non-empty numeric array.');
assert(all(isfinite(load_Coeff(:))), ...
    'Compute_FEM_Data:InvalidLoadCoeff', ...
    'load_Coeff must contain only finite values.');
assert(isnumeric(delta) && isscalar(delta) && isnumeric(P) && isscalar(P), ...
    'Compute_FEM_Data:InvalidBoundaryData', ...
    'delta and P must be numeric scalars.');
assert(isfinite(delta) && isfinite(P), ...
    'Compute_FEM_Data:InvalidBoundaryData', ...
    'delta and P must be finite scalar values.');

% Define problem data and allocate per-mesh solution containers.
[meshSize, solutionSize, qFunc, loadFunc, x, ...
    uFEMLin, uFEMCub, uExact, relTol] = ...
    Def_Problem(numElements, q_Type, load_Coeff, q_Coeff, delta, P);

for idx = 1:numel(numElements)
    [uFEMLin{idx}, uFEMCub{idx}] = Calc_FEM_Sol( ...
        numElements(idx), meshSize(idx), delta, P, qFunc, loadFunc, relTol);
end

[l2ErrorLin, l2ErrorCub, convergenceFactorLin, convergenceFactorCub, ...
    convergenceOrderLin, convergenceOrderCub] = ...
    Compute_Error_Summary(numElements, uExact, uFEMLin, uFEMCub, relTol);

fem_Data = struct( ...
    'num_Elements', numElements, ...
    'mesh_Size', meshSize, ...
    'q_Type', normalizedQType, ...
    'solution_Size', solutionSize, ...
    'x', x, ...
    'u_Exact', uExact, ...
    'u_FEM_Lin', {uFEMLin}, ...
    'u_FEM_Cub', {uFEMCub}, ...
    'rel_Tol', relTol, ...
    'l2_Error_Lin', l2ErrorLin, ...
    'l2_Error_Cub', l2ErrorCub, ...
    'convergence_Factor_Lin', convergenceFactorLin, ...
    'convergence_Factor_Cub', convergenceFactorCub, ...
    'convergence_Order_Lin', convergenceOrderLin, ...
    'convergence_Order_Cub', convergenceOrderCub);

assert(numel(fem_Data.u_FEM_Lin) == numel(numElements), ...
    'Compute_FEM_Data:InvalidOutput', ...
    'Linear FEM output cell count must match numElements length.');
assert(numel(fem_Data.u_FEM_Cub) == numel(numElements), ...
    'Compute_FEM_Data:InvalidOutput', ...
    'Cubic FEM output cell count must match numElements length.');
assert(isa(fem_Data.u_Exact, 'function_handle'), ...
    'Compute_FEM_Data:InvalidOutput', ...
    'u_Exact output must be a function handle.');
assert(all(isfinite(fem_Data.l2_Error_Lin)) && all(isfinite(fem_Data.l2_Error_Cub)), ...
    'Compute_FEM_Data:InvalidOutput', ...
    'Computed error summaries must be finite.');