function [meshSize, solutionSize, qFunc, loadFunc, ...
    x, uFEMLin, uFEMCub, uExact, relTol] = ...
    Def_Problem(numElements, q_Type, load_Coeff, q_Coeff, delta, P)

%DEF_PROBLEM Define mesh parameters and exact model data.

assert(isnumeric(numElements) && isvector(numElements) && ~isempty(numElements), ...
    'Def_Problem:InvalidNumElements', ...
    'numElements must be a non-empty numeric vector.');
assert(all(numElements > 0) && all(mod(numElements, 1) == 0), ...
    'Def_Problem:InvalidNumElements', ...
    'numElements must contain positive integers.');
isValidQType = (ischar(q_Type) && size(q_Type, 1) == 1 && ~isempty(q_Type)) ...
    || (isstring(q_Type) && isscalar(q_Type) && strlength(q_Type) > 0);
assert(isValidQType, ...
    'Def_Problem:InvalidQType', ...
    'q_Type must be a non-empty char or string.');
assert(isnumeric(load_Coeff) && ~isempty(load_Coeff), ...
    'Def_Problem:InvalidLoadCoeff', ...
    'load_Coeff must be a non-empty numeric array.');
assert(all(isfinite(load_Coeff(:))), ...
    'Def_Problem:InvalidLoadCoeff', ...
    'load_Coeff must contain only finite values.');
assert(isnumeric(q_Coeff) && ~isempty(q_Coeff), ...
    'Def_Problem:InvalidQCoeff', ...
    'q_Coeff must be a non-empty numeric array.');
assert(all(isfinite(q_Coeff(:))), ...
    'Def_Problem:InvalidQCoeff', ...
    'q_Coeff must contain only finite values.');
assert(isnumeric(delta) && isscalar(delta) && isnumeric(P) && isscalar(P), ...
    'Def_Problem:InvalidBoundaryData', ...
    'delta and P must be numeric scalars.');
assert(isfinite(delta) && isfinite(P), ...
    'Def_Problem:InvalidBoundaryData', ...
    'delta and P must be finite scalar values.');

[meshSize, solutionSize, qFunc, loadFunc, x, uFEMLin, uFEMCub, uExact, relTol] = ...
    Build_Problem_Data(numElements, q_Type, load_Coeff, q_Coeff, delta, P);

