function [meshSize, solutionSize, qFunc, loadFunc, ...
    x, uFEMLin, uFEMCub, uExact, relTol] = ...
    Def_Problem(numElements, q_Type, load_Coeff, q_Coeff, delta, P)

%DEF_PROBLEM Define mesh parameters and exact model data.

[meshSize, solutionSize, qFunc, loadFunc, x, uFEMLin, uFEMCub, uExact, relTol] = ...
    Build_Problem_Data(numElements, q_Type, load_Coeff, q_Coeff, delta, P);

