function normalizedQType = Normalize_Q_Type(qType)
%NORMALIZE_Q_TYPE Normalize supported q-type names to a canonical form.

assert((ischar(qType) || isstring(qType)) && strlength(string(qType)) > 0, ...
    'Normalize_Q_Type:InvalidQType', ...
    'qType must be a non-empty char or string.');
assert(~isempty(strtrim(char(qType))), ...
    'Normalize_Q_Type:InvalidQType', ...
    'qType must not be empty or whitespace-only.');

normalizedQType = lower(strtrim(char(qType)));
normalizedQType = strrep(normalizedQType, '-', '_');
normalizedQType = strrep(normalizedQType, ' ', '_');

supportedQTypes = { ...
    'q_const', ...
    'constant', ...
    'const', ...
    'q_frac_with_denom_1st_degree', ...
    'frac_with_denom_1st_degree', ...
    'frac1', ...
    'q_frac_with_denom_2nd_degree', ...
    'frac_with_denom_2nd_degree', ...
    'frac2', ...
    'exponential', ...
    'exp', ...
    'q_exp'};

assert(any(strcmp(normalizedQType, supportedQTypes)), ...
    'Normalize_Q_Type:UnsupportedQType', ...
    'Unsupported qType: %s', char(qType));
